import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import './theme-config.css'
import "./globals.css";
import NavBar from "@/components/NavBar";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from '@radix-ui/themes'
import { Inter } from "next/font/google";

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter'
 })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <Theme accentColor="lime" grayColor="mauve" panelBackground="solid" radius="large" scaling="105%">
          <NavBar />
        <main>{children}</main>
        </Theme>
      </body>
    </html>
  );
}
